version: "3"
services:
  rabbitmq:
    container_name: "some-rabbit"
    image: "rabbitmq:shopping"
    build: .
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - 'rabbitmq_data:/data'

volumes:
  rabbitmq_data: